B3/myblog/config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    member do
      get 'posts'
    end
  end
  resources :admins do
    collection do
      get 'login'
      post 'check_login'
      get 'signup'
      get 'exit'
    end
  end
  resources :posts do
    resources :comments, only: [:new, :create, :update, :destroy]
    collection do
      get 'search'
    end
  end
  resources :comments, only: [:index]
  namespace :welcome do
    resources :categories, only: [:posts] do
      member do
        get 'posts'
      end
    end
    resources :posts, only: [:index, :show] do
      resources :comments, only: [:new, :create]
      collection do
        get 'search'
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

B3/myblog/app/views/layouts/admins.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "admins", :media => "all" %>
    <%= javascript_include_tag "admins" %>
  </head>
  <body>
    <div class="container">
      <div class="col-md-4">

      </div>
      <div class="col-md-4">
        <%= yield %>
      </div>
      <div class="col-md-4">

      </div>
    </div>

  </body>
</html>

B3/myblog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><%= content_for?(:title) ? yield(:title) : "A" %></title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag "application", :media => "all" %>

        <!-- For third-generation iPad with high-resolution Retina display: -->
        <!-- Size should be 144 x 144 pixels -->
        <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

        <!-- For iPhone with high-resolution Retina display: -->
        <!-- Size should be 114 x 114 pixels -->
        <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

        <!-- For first- and second-generation iPad: -->
        <!-- Size should be 72 x 72 pixels -->
        <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

        <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
        <!-- Size should be 57 x 57 pixels -->
        <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

        <!-- For all other devices -->
        <!-- Size should be 32 x 32 pixels -->
        <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

        <%= javascript_include_tag "application" %>

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]> <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script> <![endif]-->
    </head>
    <body>

        <div class="navbar navbar-inverse navbar-static-top">
            <div class="container">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/posts">Myblog</a>
                <div class="navbar-collapse collapse navbar-responsive-collapse">
                    <ul class="nav navbar-nav">
                        <li><%= link_to "发布文章", new_post_path  %></li>
                        <li><%= link_to "留言管理", comments_path  %></li>
                        <li><%= link_to "文章管理", posts_path  %></li>
                        <li><%= link_to "分类管理", categories_path  %></li>
                        <li><%= link_to "退出登陆", exit_admins_path  %></li>
                    </ul>
                </div>
                <div>
                    <form action="/posts/search" method="get" class="navbar-form navbar-right" role="search">
                        <input class="form-control" type="text" name="search">
                        <input class="form-control" type="submit" value="search">
                    </form>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <%= yield %>
                </div>
                <div class="col-md-3">
                    <div class="well sidebar-nav">
                        <h3><%= link_to '文章分类', categories_path %></h3>
                        <ul class="nav nav-list">
                            <li class="nav-header"> </li>
                            <% Category.all.each do |i|%>
                            <li><%= link_to i.title, posts_category_path(i)  %></li>
                            <% end %>
                        </ul>
                    </div>
                    <!--/.well -->
                </div>
                <!--/span-->
            </div>
            <!--/row-->

            <footer>
                <p>&copy; Company 2016</p>
            </footer>

        </div>
        <!-- /container -->

    </body>
</html>

B3/myblog/app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "blog", :media => "all" %>
    <%= javascript_include_tag "blog" %>
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-static-top">
        <div class="container">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/posts">Myblog</a>
            <div class="navbar-collapse collapse navbar-responsive-collapse">
                <ul class="nav navbar-nav">
                    <li><%= link_to "发布文章", new_post_path  %></li>
                    <li><%= link_to "留言管理", comments_path  %></li>
                    <li><%= link_to "文章管理", posts_path  %></li>
                    <li><%= link_to "退出登陆", exit_admins_path  %></li>
                </ul>
            </div>
            <div>
                <form action="/posts/search" method="get" class="navbar-form navbar-right" role="search">
                    <input class="form-control" type="text" name="search">
                    <input class="form-control" type="submit" value="search">
                </form>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <%= yield %>
            </div>
            <div class="col-md-3">
                <div class="well sidebar-nav">
                    <h3>Sidebar</h3>
                    <ul class="nav nav-list">
                        <li class="nav-header">文章分类：</li>
                        <% Category.all.each do |i|%>
                        <li><%= link_to i.title, show_post_by_category_category_path(i)  %></li>
                        <% end %>
                    </ul>
                </div>
                <!--/.well -->
                <div id="demo">

                    <div class="list-group">

                        <a href="#" class="list-group-item active">Item 1</a>

                        <a href="#" class="list-group-item">Item 2</a>

                        <a href="#" class="list-group-item">Item 3</a>

                        <a href="#" class="list-group-item">Item 4</a>

                        <a href="#" class="list-group-item">Item 5</a>

                        ...

                    </div>

                </div>

            </div>
            <!--/span-->
        </div>
        <!--/row-->

        <footer>
            <p>&copy; Company 2016</p>
        </footer>

    </div>

  </body>
</html>

B3/myblog/app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "welcome", :media => "all" %>
    <%= javascript_include_tag "welcome" %>
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-static-top">
        <div class="container">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/welcome/posts">Myblog</a>
            <div class="navbar-collapse collapse navbar-responsive-collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
            <div>
                <form action="/welcome/posts/search" method="get" class="navbar-form navbar-right" role="search">
                    <input class="form-control" type="text" name="search">
                    <input class="form-control" type="submit" value="search">
                </form>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <%= yield %>
            </div>
            <div class="col-md-3">
                <div class="well sidebar-nav">
                    <h3>文章分类</h3>
                    <ul class="nav nav-list">
                        <li class="nav-header"></li>
                        <% Category.all.each do |i|%>
                        <li><%= link_to i.title,  posts_welcome_category_path(i)  %></li>
                        <% end %>
                    </ul>
                </div>
                <!--/.well -->
                <div class="panel panel-info">
                  <div class="panel-heading">热门文章</div>
                  <div class="panel-body">
                    <% p = Post.all.sort_by { |e| e.comments.select{|i| i.status == true }.length }
                       p.reverse!
                       i = 0
                       5.times do |i|%>
                       <blockquote cite="http://">
                         <%= link_to p[i].title, welcome_post_path(p[i])  %>
                       </blockquote>
                    <% i += 1
                  end%>

                  </div>
                </div>

            </div>
            <!--/span-->
        </div>
        <!--/row-->

        <footer>
            <p>&copy; Company 2016</p>
        </footer>

    </div>

  </body>
</html>