B3/myblog/config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    member do
      get 'posts'
    end
  end
  resources :admins do
    collection do
      get 'login'
      post 'check_login'
      get 'signup'
      get 'exit'
    end
  end
  resources :posts do
    resources :comments, only: [:new, :create, :update, :destroy]
    collection do
      get 'search'
    end
  end
  resources :comments, only: [:index]
  namespace :welcome do
    resources :categories, only: [:posts] do
      member do
        get 'posts'
      end
    end
    resources :posts, only: [:index, :show] do
      resources :comments, only: [:new, :create]
      collection do
        get 'search'
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

B3/myblog/app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :categories
  searchable do
    text :title, :content
  end
  validates :content, length: { minimum: 10,
                                maximum: 5000,
                                too_short: '内容长度应大于10',
                                too_long: '内容长度应小于5000' }
  validates :title, presence: { message: '标题不能为空' },
                    length: { maximum: 20,
                              too_long: '标题长度应小于20' }
end

B3/myblog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :require_login
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate(page: params[:page], per_page: 10).order('created_at DESC')
  end

  def search
    if params[:search].to_s == ''
      @posts = Post.paginate(page: params[:page], per_page: 10).order('created_at DESC')
      render 'index'
    else
      @query = Post.search do
        fulltext params[:search]
      end
      @posts = @query.results
      if @posts.empty?
        flash[:notice] = '搜索结果为空'
        render 'index'
      else
        render 'index'
      end
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
    @post = set_post
    @comments = @post.comments.paginate(page: params[:page], per_page: 5).order('created_at DESC')
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    category = Category.find_by(title: params[:category].to_s)
    @post = category.posts.create(post_params)
    if @post.valid?
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render 'new'
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    if Category.find_by(title: params[:category].to_s).id == @post.categories[0].id # 重新编辑时分类是否改变
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    else
      @post.destroy
      category = Category.find_by(title: params[:category].to_s)
      @post = category.posts.create(post_params)
      respond_to do |format|
        if @post.valid?
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

B3/myblog/app/controllers/welcome/posts_controller.rb
class Welcome::PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate(page: params[:page], per_page: 10).order('created_at DESC')
    render layout: 'welcome'
  end

  def search
    if params[:search].to_s == ''
      @posts = Post.paginate(page: params[:page], per_page: 10).order('created_at DESC')
    else
      @query = Post.search do
        fulltext params[:search]
      end
      @posts = @query.results
      flash[:notice] = '搜索结果为空' if @posts.empty?
    end
    render 'index', layout: 'welcome'
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
    @post = set_post
    @comments = Comment.where(post_id: params[:id].to_i, status: true)
    @comments = @comments.paginate(page: params[:page], per_page: 5)
    render layout: 'welcome'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

B3/myblog/app/helpers/posts_helper.rb
module PostsHelper
end

B3/myblog/app/views/posts/_form.html.erb
<div class="form-horizontal">
  <%= form_for(post) do |f| %>
  <div class="text-info text-center">
    <% if post.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %>
            prohibited this post from being saved:</h2>

        <ul>
            <% post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
    </div>
    <% end %>
  </div>
    <div class="form-group">
      <%= f.label :Title, :class => 'control-label col-md-2' %>
      <div class="col-md-5">
        <%= f.text_field :title, :class => 'form-control' %>
      </div>
      <div class="col-md-5">
        <%= f.label :Category, :class => 'control-label col-md-4' %>
        <div class="col-md-8">
          <select class="form-control" name="category">
            <% Category.all.each do |i| %>
            <option value="<%= i.title %>"><%=i.title %></option>
            <% end %>
          </select>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :Content, :class => 'control-label col-md-2' %>
      <div class="col-md-10">
        <%= f.kindeditor :content, :class => 'form-control', :width => '600', :height => '800'  %>
      </div>
    </div>
    <%= f.submit :提交, :class => 'btn btn-success pull-right' %>
  <% end %>

</div>

B3/myblog/app/views/posts/edit.html.erb
<div class="panel panel-info">
  <div class="panel-heading">编辑文章</div>
  <div class="panel-body">
    <%= render 'form', post: @post %>
    <div class="btn btn-success ">
      <%= link_to 'Back', posts_path %>
    </div>
  </div>
</div>

B3/myblog/app/views/posts/index.html.erb
<div class="text-warning text-center">
  <%= notice %>
</div>
<div class="panel panel-info">
    <div class="panel-heading">
        文章列表
    </div>
    <div class="panel-body">
        <% @posts.each do |post| %>
        <blockquote cite="/posts">
            <a href="/posts/<%=post.id%>">
                <p><%= post.title%></p>
            </a>
            <span>
              <small>发表于<%= post.created_at.strftime("%Y-%m-%d")%>|分类:<%= post.categories[0].title %>|评论数<%= post.comments.length%></small>
              <div class="pull-right">
                <div class="btn btn-info">
                  <%= link_to '编辑', edit_post_path(post) %>
                </div>
                <div class="btn btn-warning">
                  <%= link_to '删除', post, method: :delete, data: { confirm: 'Are you sure?' } %>
                </div>
              </div>
            </span>
        </blockquote>
        <% end %>
    </div>
    <div class="apple_pagination">
      <%= will_paginate @posts %>
    </div>
</div>

B3/myblog/app/views/posts/new.html.erb
<div class="panel panel-info">
  <div class="panel-heading">新建文章</div>
  <div class="panel-body">
    <%= render 'form', post: @post %>
    <div class="btn btn-success ">
      <%= link_to 'Back', posts_path %>
    </div>
  </div>
</div>

B3/myblog/app/views/posts/show.html.erb
<div class="text-info text-center">
  <p id="notice"><%= notice %></p>
  <% if @comment.errors.any? %>
  <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %>
          prohibited this post from being saved:</h2>

      <ul>
          <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
      </ul>
  </div>
  <% end %>
</div>


<h3 class="text-center"><%= @post.title %></h3>
<div class="panel panel-info">
  <div class="panel-heading">正文</div>
  <div class="panel-body">
    <div class="text-info newline">
      <%= @post.content.html_safe %>
    </div>
  </div>
  <div class="panel-footer">
    <span>
      发表于<%= @post.created_at.strftime("%Y-%m-%d")%>|分类：<%= @post.categories[0].title %>
      <div class="pull-right">
        <div class="btn btn-info">
          <%= link_to '编辑', edit_post_path(@post) %>
        </div>
        <div class="btn btn-warning">
          <%= link_to '删除', @post, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </span>
  </div>
</div>
<br>

<div class="panel panel-info">
    <div class="panel-heading">评论区
        <span class="badge pull-right"><%= @comments.count%></span>
    </div>
    <div class="panel-body">
        <% @comments.each do |comment| %>
        <% if !comment.id.nil? %>    <!-- 当留言失败时，失败的留言对象会保存在@post.comments数组中，坑爹-->
        <div class="panel panel-default">
            <div class="panel-body">
                <%= comment.content.html_safe%>
            </div>
            <div class="panel panel-footer">

                <% if comment.status == false %>
                <%= form_for :comment, url: post_comment_path(@post,comment.id), method: :put do |f|%>
                <span>发表于<%= comment.created_at.strftime("%Y-%m-%d")%>
                    | email:<%= comment.email %>|
                    <div class="pull-right">
                      <input type="submit" name="name" value="审核通过" class="btn btn-success">
                      <div class="btn btn-warning">
                        <%= link_to '删除', post_comment_path(@post,comment), method: :delete, data: { confirm: 'Are you sure?' } %>
                      </div>
                    </div>
                  </span>

            <%end
               else%>
                <span>发表于<%= comment.created_at.strftime("%Y-%m-%d")%>
                    | email:<%= comment.email %>
                    <div class="btn btn-warning pull-right">
                      <%= link_to '删除', post_comment_path(@post,comment), method: :delete, data: { confirm: 'Are you sure?' } %>
                    </div>
                </span>
                <%end%>
            </div>
        </div>
        <% end %>
        <% end %>
        <div class="apple_pagination">
          <%= will_paginate @comments %>
        </div>
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">
        新建评论
    </div>
    <div class="panel-body">
      <div class="form-horizontal">
        <%= form_for([@post, @post.comments.build]) do |f| %>
        <div class="form-group">
          <%= f.label :email, :class=>'col-md-2 control-label' %>
          <div class="col-md-5">
            <%= f.text_field :email, :class=>'form-control', :placeholder => 'Example: jingzf0214@gmail.com' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :content, :class=>'col-md-2 control-label' %>
          <div class="col-md-10">
            <%= f.text_area :content, :class=>'form-control', :rows => '4', :placeholder => "留言内容至少包含10个字符" %>
          </div>
        </div>
        <%= f.submit :提交, :class => 'btn btn-success pull-right'%>
        <% end %>
      </div>
    </div>
</div>