B3/myblog/config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    member do
      get 'posts'
    end
  end
  resources :admins do
    collection do
      get 'login'
      post 'check_login'
      get 'signup'
      get 'exit'
    end
  end
  resources :posts do
    resources :comments, only: [:new, :create, :update, :destroy]
    collection do
      get 'search'
    end
  end
  resources :comments, only: [:index]
  namespace :welcome do
    resources :categories, only: [:posts] do
      member do
        get 'posts'
      end
    end
    resources :posts, only: [:index, :show] do
      resources :comments, only: [:new, :create]
      collection do
        get 'search'
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

B3/myblog/app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :posts, dependent: :destroy
  validates :title, presence: { message: '标题不能为空' },
                    uniqueness: { message: '该分类已存在' },
                    length: { maximum: 5,
                              too_long: '标题长度应小于5' }
end

B3/myblog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :require_login
  # GET /categories
  # GET /categories.json
  def index
    @category = Category.new
    @categories = Category.all
  end

  def posts
    category = Category.find(params[:id])
    @posts = category.posts.paginate(page: params[:page], per_page: 10)
    render 'posts/index'
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        @categories = Category.all
        format.html { render :index }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:title)
  end
end

B3/myblog/app/controllers/welcome/categories_controller.rb
class Welcome::CategoriesController < ApplicationController
  def posts
    category = Category.find(params[:id])
    @posts = category.posts.paginate(page: params[:page], per_page: 10)
    render 'welcome/posts/index', layout: 'welcome'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:title)
  end
end

B3/myblog/app/helpers/categories_helper.rb
module CategoriesHelper
end

B3/myblog/app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

B3/myblog/app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

B3/myblog/app/views/categories/index.html.erb
<div class="text-center text-success">
  <%= notice %>
  <% if @category.errors.any? %>
  <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %>
          prohibited this post from being saved:</h2>

      <ul>
          <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
      </ul>
  </div>
  <% end %>
</div>
<div class="panel panel-info">
  <div class="panel-heading">
    新建分类
  </div>
  <div class="panel-body">
    <div class="form-horizontal">
      <%= form_for :category, url: categories_path do |f| %>
      <div class="form-group">
        <%= f.label :分类, :class => 'control-label col-md-2' %>
        <div class="col-md-8">
          <%= f.text_field :title, :class => 'form-control', :placeholder => "不能为空且不要多于五个字符" %>
        </div>
        <div class="col-md-2">
          <%= f.submit :提交, :class => 'btn btn-success pull-right' %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

<div class="panel panel-info">
  <div class="panel-heading">
    分类管理
  </div>
  <div class="panel-body">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>Category</th>
          <th>Number</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |i| %>
        <tr>
          <th><%= i.title %></th>
          <th><%= i.posts.count %></th>
          <th>
            <div class="btn btn-success pull-right">
              <%= link_to "Delete", category_path(i), method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </th>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

B3/myblog/app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

B3/myblog/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>