B3/myblog/config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    member do
      get 'posts'
    end
  end
  resources :admins do
    collection do
      get 'login'
      post 'check_login'
      get 'signup'
      get 'exit'
    end
  end
  resources :posts do
    resources :comments, only: [:new, :create, :update, :destroy]
    collection do
      get 'search'
    end
  end
  resources :comments, only: [:index]
  namespace :welcome do
    resources :categories, only: [:posts] do
      member do
        get 'posts'
      end
    end
    resources :posts, only: [:index, :show] do
      resources :comments, only: [:new, :create]
      collection do
        get 'search'
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

B3/myblog/app/views/admins/_form.html.erb
<%= form_for(admin) do |f| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

B3/myblog/app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

B3/myblog/app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admins</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.name %></td>
        <td><%= admin.password %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

B3/myblog/app/views/admins/login.html.erb
<br><br><br><br><br><br><br><br>
<div class="text-warning text-center">
  <%= notice %>
</div>
<div class="panel panel-info">
  <div class="panel-heading">
    管理员登陆
  </div>
  <div class="panel-body">
    <div class="form-horizontal">
      <%= form_for :admin, url: check_login_admins_path do |f| %>
      <div class="form-group">
        <%= f.label :账号, :class => 'control-label col-md-2' %>
        <div class="col-md-10">
          <%= f.text_field :name, :class => 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :密码, :class => 'control-label col-md-2' %>
        <div class="col-md-10">
          <%= f.password_field :password, :class => 'form-control' %>
        </div>
      </div>
      <%= f.submit :提交, :class => 'btn btn-success pull-right' %>
      <% end %>
    </div>
  </div>
</div>

B3/myblog/app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admins_path %>

B3/myblog/app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @admin.password %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

B3/myblog/app/views/admins/signup.html.erb
<h1>管理员注册</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', login_admins_path %>